version: '3.8'

x-environment: &default-environment
  MINIO_ACCESS_KEY: v6COFScXBCIfZFsqYNH0
  MINIO_SECRET_KEY: 9LMHiwoKXo5ekF7ovYBExDx4fifBj1ydzJam64on
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

services:
  users_api_database:
    image: mongo:6.0.9
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_volume:/data/db

  api_s3:
    build: ./s3-worker
    ports:
      - "8001:8001"
    environment:
      <<: [ *default-environment ]
      MINIO_ENDPOINT_URL: http://host.docker.internal:9000
    restart: always
    volumes:
      - ./:/app

  s3_storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      <<: [ *default-environment ]
    volumes:
      - s3_data_volume:/data



volumes:
  mongodb_data_volume:
  s3_data_volume:
