version: '3.8'

services:
  users_api:
    build: ./users-api
    container_name: users_api
    ports:
      - "8080:8080"
    environment:
      - INIT_TABLES=
      - DATABASE_URL=
      - DB_NAME=
      - APP_STAGE=
      - S3_WORKER_API=
    restart: always
    depends_on:
      - users_api_database
    volumes:
      - ./:/app

  users_api_database:
    image: mongo:6.0.9
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_volume:/data/db

  telegram_bot:
    build: ./telegram-bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=
      - API_URL=
      - TEMP_STATIC_PATH=

  api_s3:
    build: ./s3-worker
    ports:
      - "8001:8001"
    environment:
      - MINIO_ACCESS_KEY=
      - MINIO_SECRET_KEY=
      - MINIO_ENDPOINT_URL=
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
    restart: always
    volumes:
      - ./:/app

  s3_storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=
      - MINIO_SECRET_KEY=
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
    volumes:
      - ./s3-data:/data



volumes:
  mongodb_data_volume:
